latex_template_packages = r'''\documentclass[12pt]{report}
\usepackage[a4paper]{geometry}
\usepackage[myheadings]{fullpage}
\usepackage{fancyhdr}
\usepackage{graphicx, wrapfig, subcaption, setspace, booktabs}
\usepackage[T1]{fontenc}
\usepackage{fourier}
\usepackage[protrusion=true, expansion=true]{microtype}
\usepackage[english]{babel}
\usepackage{sectsty}
\usepackage{amsmath}
\usepackage[table]{xcolor}
\usepackage{listings}
\usepackage{hyperref}
\usepackage{booktabs}
\usepackage{titlesec}
\usepackage{lastpage}
\linespread{1.3}
\titlespacing\section{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
\titlespacing\subsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
\titlespacing\subsubsection{0pt}{12pt plus 4pt minus 2pt}{0pt plus 2pt minus 2pt}
\setlength\parindent{0pt}
\hypersetup{
    colorlinks,
    linkcolor={black},
    citecolor={blue!50!black},
    urlcolor={blue!80!black}
}
\newcommand{\HRule}[1]{\rule{\linewidth}{#1}}
\onehalfspacing

\pagestyle{fancy}
\fancyhf{}
\setlength\headheight{15pt}
\fancyhead[R]{FANCYHEAD GOES HERE}
\fancyfoot[R]{Page \thepage\ of \pageref{LastPage}}
\lstset{
basicstyle=\small\ttfamily,
columns=flexible,
breaklines=true
}
\renewcommand*\thesection{\arabic{section}}
\begin{document}'''
latex_template_title = r'''\title{ \normalsize \textsc{}
		\\ [2.0cm]
		\HRule{0.5pt} \\
		\LARGE \textbf{\uppercase{REGEXTITLEHEREREGEX
		 EXECUTIVE SUMMARY OF PRELIMINARY RESULTS}}
		\HRule{2pt} \\ [0.5cm]
		\normalsize \today \vspace*{5\baselineskip}}
\date{}
\author{Automatically generated by MARPT}
\maketitle
\tableofcontents
\newpage
\sectionfont{\scshape}'''
latex_template_executive_summary = r'''\section{Executive Summary}
This report was generated to provide the senior management of REGEXTITLEHEREREGEX with information from the preliminary information gathering and vulnerability analysis steps taken.REGEXRISKSTATEMENTREGEX '''
latex_template_technical_specifics = r'''\newpage\section{Technical Specifics}
Beneath is information on the Hosts that have been scanned so far, including the IP Address, Port and discovered Vendors. Information on potential vulnerabilities identified and the severity scores of each is also available.'''
latex_template_results_table = r'''\begin{center}
\scalebox{1}{
\begin{tabular}{lll}
\hline
\multicolumn{3}{c}{Host information} \\
\hline
Host & Ports & OS\\
\hlineREGEXIPPORTTABLEHEREREGEX\hline
\end{tabular}}
\end{center}'''
latex_template_devices_results_table = r'''\begin{center}
\begin{equation*}
\scalebox{0.9}{\hspace*{-4cm}\begin{tabular}{ | c | c |}
\hline
Host & Devices  \\
\hline REGEXDEVICETABLEHEREREGEX\hline
\end{tabular}}
\end{equation*}
\end{center}'''
latex_template_technical_specifics_scan_information = r'''\subsubsection{Scan information}
Start time: REGEXTIMESTARTREGEX \\
End Time: REGEXTIMEENDREGEX \\'''
latex_template_technical_specifics_overall_severity_results = r'''\subsection{Overall results summary}\begin{center}
\scalebox{2.2}{
\begin{tabular}{lr}
\multicolumn{2}{c}{Overall summary of vulnerabilities} \\
\hline
REGEXSEVERITYOVERALLHEREREGEX
\end{tabular}}
\end{center}'''
latex_template_technical_specifics_perhost_severity = r'''
\begin{center}
\scalebox{1.5}{
\begin{tabular}{lr}
\multicolumn{2}{c}{Overall summary of vulnerabilities} \\
\hline
REGEXPERHOSTSEVERITYREGEX
\end{tabular}}
\end{center}'''
latex_template_technical_specifics_cve_cwe_cvss_table = r'''\begin{center}
\scalebox{2.2}{
\begin{tabular}{lr}
\hline
\multicolumn{2}{c}{REGEXCVEIDREGEX Information} \\
\hline
CWE & REGEXCWEIDREGEX\\
CVSS Score & REGEXCVSSSCOREREGEX\\
\hline
\end{tabular}}
\end{center}'''
latex_template_technical_specifics_access_table = r'''\paragraph{Access}
\begin{equation*}
\scalebox{0.9}{\hspace*{-4cm}\begin{tabular}{ | c | c | c |}
\hline
Vector & Complexity & Authentication  \\
\hline REGEXACCESSTABLEREGEX\\\hline
\end{tabular}}
\end{equation*}'''
latex_template_technical_specifics_impact_table = r'''\paragraph{Impact}
\begin{equation*}
\scalebox{0.9}{\hspace*{-4cm}\begin{tabular}{ | c | c | c |}
\hline
Confidentiality & Integrity & Availability  \\
\hline REGEXIMPACTTABLEREGEX \\\hline
\end{tabular}}
\end{equation*}'''
latex_template_cve_table = r'''\subsubsection{Port REGEXPORTHERE}
\begin{equation*}
\scalebox{0.9}{\hspace*{-2cm}\begin{tabular}{ | c | c | c |}
\hline
CVE Number & Severity & CVE Link \\
\hline 
REGEXCVETABLEREGEX
\hline
\end{tabular}}
\end{equation*}'''
latex_template_raw_results = r'''\newpage\section{Raw Scripts Information}
\begin{lstlisting}
REGEXSCRIPTSTUFFREGEX
\end{lstlisting}
\pageref{LastPage}
\end{document}'''
latex_template_executive_summary_risk_high = r'''Initial results show HIGH risk to the tested infrastructure. An immediate risk assessment should be completed to allow controls to be implemented to reduce the risk to a manageable level as there is a high probability of a threat occuring.'''
latex_template_executive_summary_risk_medium = r'''Initial results show MEDIUM risk to the tested infrastructure. A risk assessment should be completed soon to allow controls to be implemented to reduce the risk to a manageable level as there is a medium probability of a threat occuring.'''
latex_template_executive_summary_risk_low = r'''Initial results show LOW risk to the tested infrastructure. A risk assessment should be planned to allow controls to be implemented to reduce the risk to a manageable level as there is a low probability of a threat occuring.'''
latex_template_executive_summary_risk_none = r'''Initial results show MEDIUM risk to the tested infrastructure. No steps should be taken until further tests have been run as initial results show no probability of a threat occuring.'''
